<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="css-playground">
    <h4><?= __('LESS mixins'); ?></h4>
    <p class="paragraph-style">This is a CSS playground</p>
    <p class="paragraph-italic">This is a CSS playground</p>

    <hr/>
    <h4><?= __('LESS mixins'); ?></h4>
    <span class="round-icon-yellow"></span>
    <span class="round-icon-green"></span>
    <span class="round-icon-blue"></span>
    <span class="round-icon-red"></span>
</div>
