<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Laminas\Escaper\Escaper $escaper */
?>
<li class="link authorization-link--jslibs-js" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a href="/jsplayground/jslibs/index" title="<?= $escaper->escapeHtml('Packt1Link'); ?>">
        <span><?= __('JS Libs Samples'); ?></span>
    </a>
</li>


<li class="link authorization-link--jslibs-solutions" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a href="/jsplayground/jslibs/solutions" title="<?= $escaper->escapeHtml('Packt1Link'); ?>">
        <span><?= __('JS Libs Solutions'); ?></span>
    </a>
</li>
