<div class="code">
    <h2>Hello from the Footer - I come from all <code>page_layout/1column.xml!</code></h2>
    <p>I should be visible on all pages with 1 column layout... but I'm also visible everywhere. <br />
        It is because this file: <code>vendor/magento/module-theme/view/frontend/page_layout/2columns-left.xml</code>
        <br />
        uses an <code>update</code> handle Layout XML instruction
    </p>
    <pre>&lt;update handle="1column" /&gt;</pre>
    <hr />
</div>
