<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Laminas\Escaper\Escaper $escaper */
?>
<li class="link authorization-link--knockout-js" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a href="/jsplayground/knockout/index/" title="<?= $escaper->escapeHtml('Packt1Link'); ?>">
        <span><?= __('KnockoutJS Samples'); ?></span>
    </a>
</li>

<li class="link authorization-link--knockout-js-solutions" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a href="/jsplayground/knockout/solutions/" title="<?= $escaper->escapeHtml('Packt1Link'); ?>">
        <span><?= __('KnockoutJS Solutions'); ?></span>
    </a>
</li>


