<!-- exercise 11 solution, Chapter 6 -->
<?php
/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>><i class="fa-solid fa-users-gear"></i>
    </a>
</li>
<!-- /end solution -->
